services:
  frontend:
    build:
      context: ./UI
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - mynetwork
    depends_on:
      - backend
  backend:
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://database:3307/toprefunder
      - spring.datasource.username=root
      - spring.datasource.password=root
    depends_on:
      - database
    networks:
      - mynetwork
  database:
    image: mysql:8.0-oracle
    ports:
      - 3307:3306
    networks:
      - mynetwork
    volumes:
      - mysql_volume:/var/lib/mysql
    environment:
      # - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=toprefunder

volumes:
  mysql_volume:

networks:
  mynetwork:
    driver: bridge
