spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://tomcoderrefund.mysql.database.azure.com/toprefunder?useSSL=true
    url: jdbc:mysql://localhost:3307/toprefunder
    username: root
    password: root

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 104840287910-ohrflb5ho2a38cp98bpbustqpsng4ntm.apps.googleusercontent.com
            client-secret: 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

          github:
            client-id: 78dd35883295d65e8c5b
            client-secret: 88e8cbcee1a052205be967e0958f1e1bb5cf8377
server:
  port: 8081


  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    root: warn
